Models/ErrorViewModel.cs
namespace Nutricionista.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/Paciente.cs
using System.ComponentModel.DataAnnotations;

namespace Nutricionista.Models
{
    public class Paciente
    {
        public int Id { get; set; }
        public string Nombre { get; set; }

        public string Sexo { get; set; }

        [Display(Name = "Fecha de Nacimiento"), DataType(DataType.Date)]
        public DateTime FechaNacimiento { get; set; }

        public String Email { get; set; }

        public double Peso { get; set; }

        public double Estatura { get; set; }
    }
}

Models/PacienteViewModel.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using System;

namespace Nutricionista.Models
{
    public class PacienteViewModel
    {
        public List<Paciente> Pacientes { get; set; }

        public SelectList Genero => new SelectList(new[]
        {
            new { Id = "M", Value = "Masculino" },
            new { Id = "F", Value = "Femenino" },
            new { Id = "O", Value = "Otro" }
        }, "Id", "Value");

        public double IMC(Paciente paciente) => paciente.Peso / Math.Pow((paciente.Estatura / 100), 2); 

        public int Edad(Paciente paciente) => DateTime.Now.Year - paciente.FechaNacimiento.Year;

        public string IMCString(Paciente paciente)
        {
            var imc = IMC(paciente);
            return imc < 18.5 ? "Bajo peso" : imc < 24.9 ? "Normal" : imc < 29.9 ? "Sobrepeso" : "Obesidad";
        }

        public string IMCColor(Paciente paciente)
        {
            var imc = IMC(paciente);
            return imc < 18.5 ? "text-warning" : imc < 24.9 ? "text-success" : imc < 29.9 ? "text-warning" : imc < 34.9 ? "text-danger" : "text-danger";
        }
    }
}

Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Nutricionista.Models;

namespace Nutricionista.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/PacientesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Nutricionista.Data;
using Nutricionista.Models;

namespace Nutricionista.Controllers
{
    public class PacientesController : Controller
    {
        private readonly NutricionistaContext _context;

        public PacientesController(NutricionistaContext context)
        {
            _context = context;
        }

        // GET: Pacientes
        public async Task<IActionResult> Index()
        {
            var pacientes = await _context.Paciente.ToListAsync();
            var viewModel = new PacienteViewModel
            {
                Pacientes = pacientes
            };

            return View(viewModel);
        }

        // GET: Pacientes/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var paciente = await _context.Paciente
                .FirstOrDefaultAsync(m => m.Id == id);
            var viewModel = new PacienteViewModel
            {
                Pacientes = new List<Paciente> { paciente }
            };

            if (paciente == null)
            {
                return NotFound();
            }

            return View(viewModel);
        }

        // GET: Pacientes/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Pacientes/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Nombre,Sexo,FechaNacimiento,Email,Peso,Estatura")] Paciente paciente)
        {
            if (ModelState.IsValid)
            {
                _context.Add(paciente);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(paciente);
        }

        // GET: Pacientes/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var paciente = await _context.Paciente.FindAsync(id);
            if (paciente == null)
            {
                return NotFound();
            }
            return View(paciente);
        }

        // POST: Pacientes/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Nombre,Sexo,FechaNacimiento,Email,Peso,Estatura")] Paciente paciente)
        {
            if (id != paciente.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(paciente);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PacienteExists(paciente.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(paciente);
        }

        // GET: Pacientes/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var paciente = await _context.Paciente
                .FirstOrDefaultAsync(m => m.Id == id);
            if (paciente == null)
            {
                return NotFound();
            }

            return View(paciente);
        }

        // POST: Pacientes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var paciente = await _context.Paciente.FindAsync(id);
            if (paciente != null)
            {
                _context.Paciente.Remove(paciente);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool PacienteExists(int id)
        {
            return _context.Paciente.Any(e => e.Id == id);
        }
    }
}

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/Pacientes/Create.cshtml
@model Nutricionista.Models.Paciente

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Paciente</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Nombre" class="control-label"></label>
                <input asp-for="Nombre" class="form-control" />
                <span asp-validation-for="Nombre" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Sexo" class="control-label"></label>
                <input asp-for="Sexo" class="form-control" />
                <span asp-validation-for="Sexo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FechaNacimiento" class="control-label"></label>
                <input asp-for="FechaNacimiento" class="form-control" />
                <span asp-validation-for="FechaNacimiento" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Peso" class="control-label"></label>
                <input asp-for="Peso" class="form-control" />
                <span asp-validation-for="Peso" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Estatura" class="control-label"></label>
                <input asp-for="Estatura" class="form-control" />
                <span asp-validation-for="Estatura" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Pacientes/Delete.cshtml
@model Nutricionista.Models.Paciente

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Paciente</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nombre)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nombre)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Sexo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Sexo)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FechaNacimiento)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FechaNacimiento)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Email)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Peso)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Peso)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Estatura)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Estatura)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Views/Pacientes/Details.cshtml
@model Nutricionista.Models.PacienteViewModel

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Paciente</h4>
    <hr />
    <dl class="row">
        @if (Model.Pacientes.Any())
        {
            var paciente = Model.Pacientes.First();

            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => paciente.Nombre)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => paciente.Nombre)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => paciente.Sexo)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => paciente.Sexo)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => paciente.FechaNacimiento)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => paciente.FechaNacimiento)
            </dd>
            <dt class="col-sm-2">
                Edad
            </dt>
            <dd class="col-sm-10">
                @Model.Edad(paciente)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => paciente.Email)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => paciente.Email)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => paciente.Peso)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => paciente.Peso)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => paciente.Estatura)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => paciente.Estatura)
            </dd>
            <dt class="col-sm-2">
                IMC
            </dt>
            <dd class="col-sm-10">
                @Model.IMC(paciente)
            </dd>
            <dt class="col-sm-2">
                Condición
            </dt>
            <dd class="col-sm-10 @Model.IMCColor(paciente)">
                @Model.IMCString(paciente)
            </dd>
        }
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Pacientes.First().Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Views/Pacientes/Edit.cshtml
@model Nutricionista.Models.Paciente

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Paciente</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Nombre" class="control-label"></label>
                <input asp-for="Nombre" class="form-control" />
                <span asp-validation-for="Nombre" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Sexo" class="control-label"></label>
                <input asp-for="Sexo" class="form-control" />
                <span asp-validation-for="Sexo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FechaNacimiento" class="control-label"></label>
                <input asp-for="FechaNacimiento" class="form-control" />
                <span asp-validation-for="FechaNacimiento" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Peso" class="control-label"></label>
                <input asp-for="Peso" class="form-control" />
                <span asp-validation-for="Peso" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Estatura" class="control-label"></label>
                <input asp-for="Estatura" class="form-control" />
                <span asp-validation-for="Estatura" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Pacientes/Index.cshtml
@model Nutricionista.Models.PacienteViewModel

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Pacientes[0].Nombre)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Pacientes[0].Sexo)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Pacientes[0].FechaNacimiento)
            </th>
            <th>Edad</th>
            <th>
                @Html.DisplayNameFor(model => model.Pacientes[0].Email)
            </th>   
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var paciente in Model.Pacientes)
        {
            <tr>
                <td>
                    @Html.DisplayFor(model => paciente.Nombre)
                </td>
                <td>
                    @Html.DisplayFor(model => paciente.Sexo)
                </td>
                <td>
                    @Html.DisplayFor(model => paciente.FechaNacimiento)
                </td>
                <td>
                    @Model.Edad(paciente)
                </td>
                <td>
                    @Html.DisplayFor(model => paciente.Email)
                </td>
                <td>
                    <a asp-action="Edit" asp-route-id="@paciente.Id">Edit</a> |
                    <a asp-action="Details" asp-route-id="@paciente.Id">Details</a> |
                    <a asp-action="Delete" asp-route-id="@paciente.Id">Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Nutricionista</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Nutricionista.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Nutricionista</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse d-sm-inline-flex justify-content-between collapse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Pacientes" asp-action="Index">
                                Pacientes
                            </a>
                            </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - Nutricionista - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>